#!/bin/bash

while true; do
    clear
    echo "Iniciar Wordpress"
    echo
    echo "1. Lanzar Wordpress usando un servidor Puppet"
    echo "2. Lanzar Wordpress usnado sin un servidor Puppet"
    echo "3. Salir"
    echo
    read -p "Selecciona una opción: " option
    echo

    case $option in
        1)
            cd server
            vagrant up
            break
            ;;
        2)
            cd standalone
            vagrant up
            break
            ;;
        3)
            exit 0
            ;;
        *)
            echo "Opción inválida. Por favor, selecciona una opción válida."
            read -p "Presiona Enter para continuar..."
            ;;
    esac
done
