$initial_db = <<SCRIPT
sudo timedatectl set-timezone America/Mexico_City
sudo -i rpm -Uvh https://yum.puppet.com/puppet8-release-el-8.noarch.rpm
#  sudo dnf update -y && sudo dnf upgrade -y && sudo dnf install puppet-agent -y
sudo dnf install puppet-agent -y
sudo -i puppet config print | grep -i modules
sudo -i puppet module install puppet-firewalld
sudo -i puppet module install puppetlabs-mysql
SCRIPT

$initial_site = <<SCRIPT
sudo timedatectl set-timezone America/Mexico_City
sudo -i rpm -Uvh https://yum.puppet.com/puppet8-release-el-8.noarch.rpm
#  sudo dnf update -y && sudo dnf upgrade -y && sudo dnf install puppet-agent curl unzip -y
sudo dnf install puppet-agent -y
sudo -i puppet config print | grep -i modules
sudo -i puppet module install puppet-firewalld
sudo -i puppet module install puppet-selinux
sudo -i puppet module install puppet-archive
SCRIPT

$initial_proxy = <<SCRIPT
sudo timedatectl set-timezone America/Mexico_City
sudo -i rpm -Uvh https://yum.puppet.com/puppet8-release-el-8.noarch.rpm
#  sudo dnf update -y && sudo dnf upgrade -y && sudo dnf install puppet-agent curl unzip -y
sudo dnf install puppet-agent -y
sudo -i puppet config print | grep -i modules
sudo -i puppet module install puppet-firewalld
sudo -i puppet module install puppet-selinux
sudo -i puppet module install puppet-nginx
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.synced_folder "hosts", "/opt/puppetlabs/puppet/modules/hosts"

  config.vm.define :wordpress_db do |db|
    db.vm.provision "shell", inline: $initial_db
    db.vm.hostname = "db.unir.actividad1.mx"
    db.vm.network "private_network", ip: "192.168.56.10"

    db.vm.provision "puppet" do |puppet|
      puppet.manifest_file = "database.pp"
      puppet.options = "--verbose --summarize"
    end
  end

  config.vm.define :wordpress_site do |app|
    app.vm.provision "shell", inline: $initial_site
    app.vm.hostname = "site.unir.actividad1.mx"
    app.vm.network "private_network", ip: "192.168.56.20"
    app.vm.synced_folder "wordpress", "/opt/puppetlabs/puppet/modules/wordpress"

    app.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "apache.pp"
      puppet.options = "--verbose --summarize"
    end
  end

  config.vm.define :wordpress_proxy do |proxy|
    proxy.vm.provision "shell", inline: $initial_proxy
    proxy.vm.hostname = "proxy.unir.actividad1.mx"
    proxy.vm.network "private_network", ip: "192.168.56.30"
    proxy.vm.network "forwarded_port", guest: 8080, host: 1800
    proxy.vm.synced_folder "proxy", "/opt/puppetlabs/puppet/modules/proxy"

    proxy.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "nginx.pp"
      puppet.options = "--verbose --summarize"
    end
  end
end
